paths:
  /produtos:
    get:
      summary: Lista todos os produtos
      operationId: Produtos_findAll
      tags:
        - Produtos
      responses:
        '200':
          description: Sucesso
    post:
      summary: Cria um novo produto
      operationId: Produtos_create
      tags:
        - Produtos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProdutoDto'
      responses:
        '201':
          description: Produto criado

  /produtos/{id}:
    get:
      summary: Busca um produto por ID
      operationId: Produtos_findOne
      tags:
        - Produtos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sucesso

components:
  schemas:
    CreateProdutoDto:
      type: object
      required:
        - nome
        - descricao
        - preco
        - categoria
        - imagemPrincipal
        - imagensAdicionais
        - userId
        - regiaoAtendimento # Novo campo obrigatório
      properties:
        nome:
          type: string
          example: "Consultoria de TI"
        descricao:
          type: string
        preco:
          type: string # MUDANÇA: Era number, agora é string para permitir margens
          example: "R$ 120,00 - R$ 200,00"
        categoria:
          type: string
        imagemPrincipal:
          type: string
          format: uri
          description: "URL da imagem de capa do produto"
          example: "https://minhaimagem.com/principal.jpg"
        imagensAdicionais:
          type: array
          description: "Lista com URLs de fotos extras do produto"
          items:
            type: string
            format: uri
          example: 
            - "https://minhaimagem.com/foto2.jpg"
            - "https://minhaimagem.com/foto3.jpg"  
        userId:
          type: string
        regiaoAtendimento: # NOVO CAMPO
          type: string
          example: "Bandeirantes, Itambaracá ou a domicílio"
          description: "Cidades atendidas ou tipo de atendimento"