openapi: 3.0.0
info:
  title: API Elas Conectadas
  description: Arquitetura Orientada a Contratos (Modular)
  version: "1.0"
servers:
  - url: https://api.elasconectadas.com
    description: Servidor de Produção
  - url: http://127.0.0.1:8080
    description: Servidor de Desenvolvimento Local

paths:
  # Módulo de uploads
  /upload/imagem:
    $ref: './modules/upload.yaml#/paths/~1upload~1imagem'

  # Módulo de posts
  /posts/create:
    $ref: './modules/posts.yaml#/paths/~1posts~1create'
  /posts/list:
    $ref: './modules/posts.yaml#/paths/~1posts~1list'
  /posts/{id}:
    $ref: './modules/posts.yaml#/paths/~1posts~1{id}'

  # Módulo de auth
  /auth/login:
    $ref: './modules/auth.yaml#/paths/~1login'
  /auth/send:
    $ref: './modules/auth.yaml#/paths/~1send'
  /auth/request-otp:
    $ref: './modules/auth.yaml#/paths/~1request-otp'
  /auth/verify-otp:
    $ref: './modules/auth.yaml#/paths/~1verify-otp'

  # Módulo de ads
  /ads/create:
    $ref: './modules/ads.yaml#/paths/~1ads~1create'
  /ads/list:
    $ref: './modules/ads.yaml#/paths/~1ads~1list'
  /ads/{id}:
    $ref: './modules/ads.yaml#/paths/~1ads~1{id}'

  # Módulo de Produtos
  /produtos:
    $ref: './modules/products.yaml#/paths/~1produtos'
  /produtos/{id}:
    $ref: './modules/products.yaml#/paths/~1produtos~1{id}'

  # Módulo de Usuários
  /users/register:
    $ref: './modules/users.yaml#/paths/~1users~1register'
  /users/admin:
    $ref: './modules/users.yaml#/paths/~1users~1admin'
  /users:
    $ref: './modules/users.yaml#/paths/~1users'
  /users/{id}:
    $ref: './modules/users.yaml#/paths/~1users~1{id}'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token JWT obtido no login. Envie no header Authorization como Bearer <token>.
  schemas:
    LoginDto:
      $ref: './modules/auth.yaml#/components/schemas/LoginDto'
    LoginResponseDto:
      $ref: './modules/auth.yaml#/components/schemas/LoginResponseDto'
    sendEmailDto:
      $ref: './modules/auth.yaml#/components/schemas/sendEmailDto'
    requestTokenDto:
      $ref: './modules/auth.yaml#/components/schemas/requestTokenDto'
    VerifyOtpDto:
      $ref: './modules/auth.yaml#/components/schemas/VerifyOtpDto'
    UserResponseDto:
      $ref: './modules/users.yaml#/components/schemas/UserResponseDto'
    CreateUserDto:
      $ref: './modules/users.yaml#/components/schemas/CreateUserDto'
    CreateAdminDto:
      $ref: './modules/users.yaml#/components/schemas/CreateAdminDto'
    UpdateUserDto:
      $ref: './modules/users.yaml#/components/schemas/UpdateUserDto'
    ProdutoResponseDto:
      $ref: './modules/products.yaml#/components/schemas/ProdutoResponseDto'
    CreateProdutoDto:
      $ref: './modules/products.yaml#/components/schemas/CreateProdutoDto'
    UploadResponseDto:
      $ref: './modules/upload.yaml#/components/schemas/UploadResponseDto'
    CreateAdDto:
      $ref: './modules/ads.yaml#/components/schemas/CreateAdDto'
    UpdateAdDto:
      $ref: './modules/ads.yaml#/components/schemas/UpdateAdDto'
    CreatePostDto:
      $ref: './modules/posts.yaml#/components/schemas/CreatePostDto'
    UpdatePostDto:
      $ref: './modules/posts.yaml#/components/schemas/UpdatePostDto'